- name: Build & Publish Debug APK
  uses: ShaunLWM/action-release-debugapk@0.0.7


on:
  push:
    branches:
      - action-process

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Releasing using Hub
        uses: ShaunLWM/action-release-debugapk@master
        env:
          GITHUB_TOKEN: ${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}
          APP_FOLDER: app
          RELEASE_TITLE: New Build
